name: Slackware 14.2 Docker Images

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Fetch x86 ChangeLogs
        run: |
          curl -s -f -o slackware-14.2/ChangeLog.txt.386 https://slackware.osuosl.org/slackware-14.2/ChangeLog.txt
          curl -s -f -o slackware-14.2/ChangeLog.txt.amd64 https://slackware.osuosl.org/slackware64-14.2/ChangeLog.txt

      - name: Cache Base Tarballs
        id: cache-base-tarballs
        uses: actions/cache@v3
        with:
          path: base_tarballs/
          key: ${{ runner.os }}-base-tarballs-14.2-${{ hashFiles('**/slackware-14.2/ChangeLog*', '**/scripts/build_base_image.sh') }}

      - name: Cache Docker Builds
        id: cache-docker-build
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-dockerbuild-14.2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build prerequisites
        if: steps.cache-base-tarballs.outputs.cache-hit != 'true'
        run: |
          docker run --cap-add SYS_ADMIN --security-opt apparmor:unconfined --rm -e RELEASENAME=slackware -e ARCH=i586 -e VERSION=14.2 -e CHOWN_TO="$(id -u):$(id -g)" -v "$(pwd):/data" -v "$(pwd)/scripts:/scripts" alpine:3.15 sh /scripts/build_base_image.sh
          docker run --cap-add SYS_ADMIN --security-opt apparmor:unconfined --rm -e RELEASENAME=slackware64 -e ARCH=x86_64 -e VERSION=14.2 -e CHOWN_TO="$(id -u):$(id -g)" -v "$(pwd):/data" -v "$(pwd)/scripts:/scripts" alpine:3.15 sh /scripts/build_base_image.sh
          cp *.tar base_tarballs/

      - name: Restore prerequisites
        if: steps.cache-base-tarballs.outputs.cache-hit == 'true'
        run: |
          cp base_tarballs/*tar .

      - name: Fetch Arm ChangeLog
        run: |
          curl -s -f -o slackware-14.2/ChangeLog.txt.arm https://slackware.uk/slackwarearm/slackwarearm-14.2/ChangeLog.txt

      - name: Fetch Miniroot details
        run: |
          curl -s -f -o slackware-14.2/slackarm-14.2-miniroot_details.txt https://slackware.uk/slackwarearm/slackwarearm-devtools/minirootfs/roots/slackarm-14.2-miniroot_details.txt
          curl -s -f -o slackware-14.2/slackarm-14.2-miniroot_details.txt.asc https://slackware.uk/slackwarearm/slackwarearm-devtools/minirootfs/roots/slackarm-14.2-miniroot_details.txt.asc

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          platforms: linux/amd64,linux/386,linux/arm/v5
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-next,mode=max
          context: .
          file: slackware-14.2/Dockerfile
          tags: |
            ghcr.io/${{ github.repository_owner }}/slackware:14.2-base
            ${{ github.repository_owner }}/slackware:14.2-base

      - name: Trim cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-next /tmp/.buildx-cache
