---
name: Mirror Sync
on:
  workflow_dispatch:
  push:
jobs:
  codeberg:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          show-progress: false
          persist-credentials: false

      - name: Mirror to codeberg
        run: |
          git remote add mirror "https://${{ github.repository_owner }}:${{ secrets.CODEBERG_TOKEN }}@codeberg.org/${{ github.repository }}.git"
          git push --tags --force --prune mirror "refs/remotes/origin/*:refs/heads/*"
          git remote remove mirror
