---
name: Mirror Sync
on:
  workflow_dispatch:
  push:
jobs:
  codeberg:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
        with:
          fetch-depth: 0
          show-progress: false

      - name: Mirror to codeberg
        run: |
          git remote add mirror "https://${{ github.repository_owner }}:${{ secrets.CODEBERG_TOKEN }}@codeberg.org/${{ github.repository }}.git"
          git push --tags --force --prune mirror "refs/remotes/origin/*:refs/heads/*"
          git remote remove mirror
